# Server Settings
server:
  port: 8080

# Application Name
spring:
  application:
    name: order-management

  # Database Settings (Temporary)
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # H2 Console Settings (for development)
  h2:
    console:
      enabled: true
      path: /h2-console