# Common Application Settings
spring:
  application:
    name: order-management

  # This tells Spring which profile to use IF none is specified.
  # For our local work, we always want to use the 'dev' settings.
  profiles:
    active: dev

server:
  port: 8080 # Common port, but 'prod' profile can override it.